-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Vært: 127.0.0.1:3306
-- Genereringstid: 05. 10 2023 kl. 10:06:40
-- Serverversion: 8.0.31
-- PHP-version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `books`
--

-- --------------------------------------------------------

--
-- Struktur-dump for tabellen `produkter`
--

DROP TABLE IF EXISTS `produkter`;
CREATE TABLE IF NOT EXISTS `produkter` (
  `prodId` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `prodTitel` varchar(100) CHARACTER SET latin1 COLLATE latin1_danish_ci NOT NULL,
  `prodAuthor` varchar(100) CHARACTER SET latin1 COLLATE latin1_danish_ci NOT NULL,
  `prodGenre` varchar(100) CHARACTER SET latin1 COLLATE latin1_danish_ci NOT NULL,
  `prodPublisher` varchar(100) CHARACTER SET latin1 COLLATE latin1_danish_ci NOT NULL,
  `prodLanguage` varchar(100) CHARACTER SET latin1 COLLATE latin1_danish_ci NOT NULL,
  `prodPublishDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `prodFormat` varchar(100) CHARACTER SET latin1 COLLATE latin1_danish_ci NOT NULL,
  `prodPages` int NOT NULL,
  `prodPrice` decimal(8,2) NOT NULL,
  `prodDescription` text CHARACTER SET latin1 COLLATE latin1_danish_ci,
  `prodBillede` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`prodId`)
) ENGINE=MyISAM AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Data dump for tabellen `produkter`
--

INSERT INTO `produkter` (`prodId`, `prodTitel`, `prodAuthor`, `prodGenre`, `prodPublisher`, `prodLanguage`, `prodPublishDate`, `prodFormat`, `prodPages`, `prodPrice`, `prodDescription`, `prodBillede`) VALUES
(41, 'Terminalen', 'Michael Katz Krefeld ', 'Krimi', 'Politikens Forlag', 'Dansk', '2023-10-06 00:00:00', 'Paperback', 408, '229.95', '<p>&rdquo;Terminalen&rdquo; er 8. bind i Michael Katz Krefelds popul&aelig;re serie om Ravn. En for&aring;rsdag bliver Ravns bedste venner Eduardo og Belindas lille s&oslash;n bortf&oslash;rt af en psykisk syg kvinde, men heldigvis finder de hurtigt drengen i live, og kvinden bliver anholdt. Ved et tilf&aelig;lde lander sagen p&aring; det advokatkontor, hvor Ravn er blevet hyret som efterforsker, og modvillig f&aring;r han til opgave at assistere i forsvaret af kvinden. Aff&aelig;ren tager dog en uventet drejning, da det under varet&aelig;gtsf&aelig;ngslingen viser sig, at hun har v&aelig;ret udsat for bestialske eksperimenter, der har skadet hendes hjerne, og at hun m&aring;ske faktisk er uskyldig. Langsomt f&aring;r Ravn viklet sig dybere og dybere ind i sagen, der f&oslash;rer ham tilbage til et af psykiatriens m&oslash;rkeste kapitler, men ogs&aring; p&aring; sporet af en skruppell&oslash;s organisation, der ikke skyr nogen midler for at bevare hemmeligheden om deres projekt og ikke mindst om... Terminalen.</p>', 'Terminalen.jpg'),
(40, 'Gobler ældes baglæns ', 'Nicklas Brendborg', 'Sundhed/Livsstil ', 'Grønningen 1', 'Dansk', '2021-03-04 00:00:00', 'Hardcover', 324, '269.94', '<p>I &rdquo;Gopler &aelig;ldes bagl&aelig;ns\" fort&aelig;ller Nicklas Brendborg historien om videnskabens &aring;relange kamp mod aldring og giver samtidig sine bud p&aring;, hvad der skal til for at forl&aelig;nge livet.</p>', 'Gobler-ældes-baglæns.jpg'),
(42, 'It ends with us', 'Colleen Hoover', 'Engelsk fiktion', 'Simon & Schuster', 'Engelsk', '2016-08-02 00:00:00', 'Paperback', 318, '164.93', '<p>Sometimes the one who loves you is the one who hurts you the most. Lily hasn\'t always had it easy, but that\'s never stopped her from working hard for the life she wants. She\'s come a long way from the small town in Maine where she grew up - she graduated from college, moved to Boston, and started her own business. So when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily\'s life suddenly seems almost too good to be true. Ryle is assertive, stubborn, maybe even a little arrogant. He\'s also sensitive, brilliant, and has a total soft spot for Lily, but Ryle\'s complete aversion to relationships is disturbing. Even as Lily finds herself becoming the exception to his \"no dating\" rule, she can\'t help but wonder what made him that way in the first place. As questions about her new relationship overwhelm her, so do thoughts of Atlas Corrigan - her first love and a link to the past she left behind. He was her kindred spirit, her protector. When Atlas suddenly reappears, everything Lily has built with Ryle is threatened. With this bold and deeply personal novel, It Ends With Us is a heart-wrenching story and an unforgettable tale of love that comes at the ultimate price.</p>', 'It ends with us.jpg'),
(43, 'Twisted love', 'Ana Huang', 'Engelsk fiktion', 'Piaktus Books', 'Engelsk', '2022-05-05 00:00:00', 'Paperback', 367, '129.94', '<p>Discover the addictive world of the Twisted series from TikTok sensation, Ana Huang! He has a heart of ice ... but for her, he\'d burn the world. Alex Volkov is a devil blessed with the face of an angel and cursed with a past he can\'t escape. Driven by a tragedy that has haunted him for most of his life, his ruthless pursuits for success and vengeance leave little room for matters of the heart. But when he\'s forced to look after his best friend\'s sister, he starts to feel something in his chest: A crack. A melt. A fire that could end his world as he knew it. Ava Chen is a free spirit trapped by nightmares of a childhood she can\'t remember. But despite her broken past, she\'s never stopped seeing the beauty in the world ... including the heart beneath the icy exterior of a man she shouldn\'t want. Her brother\'s best friend. Her neighbour. Her saviour and her downfall. Theirs is a love that was never supposed to happen - but when it does, it unleashes secrets that could destroy them both ... and everything they hold dear. Twisted Love is a brother\'s best friend/opposites attract romance with a hint of suspense. It\'s book one in the Twisted series but can be read as a standalone.</p>', 'twisted-love.jpg'),
(46, 'Offer 2117', 'Jussi Adler-Olsen', 'Krimi', 'Politikens Forlag', 'Dansk', '2019-06-14 00:00:00', 'Paperback', 486, '139.95', '<p>I over ti &aring;r har Assad v&aelig;ret et g&aring;defuldt kraftcenter i Afdeling Q, men en k&aelig;dereaktion af voldsomme begivenheder bringer ham p&aring; randen af total nedsmeltning. Kun en h&aring;rdt pr&oslash;vet Rose kan hj&aelig;lpe ham med at afkode de m&oslash;rke d&aelig;moner, som v&aelig;kkes af den spanske journalist Joan Aiguaders d&aelig;kning af en flygtnings tragiske d&oslash;d. Med Assad i centrum begynder tretten dages nervepirrende nedt&aelig;lling mod den ultimative katastrofe midt i Europas hjerte, sk&aring;nselsl&oslash;st dirigeret af den irakiske b&oslash;ddel, Ghaalib. Samtidig rystes Afdeling Q af en central kollegas d&oslash;d og af et desperat fors&oslash;g p&aring; at forhindre en indesluttet, vanvittig drengs kompromisl&oslash;se og morderiske handling. I kampen for at redde menneskeliv og f&aring; l&oslash;st Assads traumatiske dilemma kastes Carl M&oslash;rck og resten af Afdeling Q direkte ind i orkanens &oslash;je, hvor ingen bliver sk&aring;net for at tage drastiske beslutninger og for at handle med alle til r&aring;dighed st&aring;ende midler.</p>', 'offer 2117.jpg'),
(45, 'Nej nej og atter nej', 'Nina Lykke', 'Roman', 'Rosinante', 'Dansk', '2019-07-24 00:00:00', 'Paperback', 339, '199.94', '<p>En skarp og morsom roman om kernefamiliens vilk&aring;r i en tid, hvor &oslash;jeblikkets lyst er drivkraften, og intet ikke er s&aring; kompliceret, at det ikke kan forsvares med individets trang til frihed.Ingrid og Jan har v&aelig;ret gift i 25 &aring;r og bor sammen med to halvvoksne s&oslash;nner i et forstadskvarter i Oslo. Drengene lever deres eget liv og bidrager ikke med stort. For Ingrid har b&aring;de familielivet og jobbet som l&aelig;rer tabt glansen, mens Jan derimod er blevet forfremmet til afdelingsdirekt&oslash;r i departementet og overmandes af ny energi - og af Hanne, en langt yngre kollega, der begynder at f&oslash;le sig agterudsejlet p&aring; familiefronten.</p>', 'nej nej og atter nej.jpg'),
(47, 'På lige fod', 'Helle Juhl ', 'Kultur', 'Gyldendal ', 'Dansk', '2014-11-04 00:00:00', 'Hardcover', 224, '299.94', '<p>\"P&aring; lige fod. Kvindernes vej til valgretten 1915\" er Helle Juhls fort&aelig;lling om kvindernes brogede vej til valgretten - med datidens satireh&aelig;fter som rejsef&oslash;rer og med samtidige fotografier, beretninger og udsagn til at supplere fort&aelig;llingen. Undervejs m&oslash;der vi b&aring;de pr&aelig;stefruer og habitkvinder, pacifister og kanonkvinder. Men f&oslash;rst og fremmest en skare modige kvinder fra dengang, oldemor, var ung, og som p&aring; tv&aelig;rs af milj&oslash;er og baggrunde delte et br&aelig;ndende &oslash;nske om at komme p&aring; lige fod med m&aelig;ndene.</p>', 'på lige fod.jpg'),
(48, 'Lysets våben', 'Ken Follett', 'Skønlitteratur ', 'Cicero', 'Dansk', '2023-09-26 00:00:00', 'Hardcover', 719, '299.94', '<p>Traditioner bliver udfordret, den sociale sammenh&aelig;ngskraft eksploderer og Europas krige knuser h&aring;bet om fred. Den industrielle revolution buldrer frem i Kingsbridge og efterlader arbejderne uden arbejde, mens opr&oslash;ret ulmer. Samtidig forbederer Napoleon sig p&aring; at overtage verden &ndash; koste hvad det vil. Verden er i brand, og vores hovedpersoner s&aelig;tter alt ind for at redde Kingsbridges fremtid.</p>', 'lysets våben.jpg'),
(49, 'Dem der ikke tier', 'Peter Øvig Knudsen ', 'Biografi', 'Gyldendal ', 'Dansk', '2023-09-29 00:00:00', 'Hardcover', 331, '244.95', '<p>Gennem otte &aring;r har Peter &Oslash;vig Knudsen arbejdet p&aring; disse uhyggelige og modbydelige sager om de organiserede seksuelle overgreb, der blev beg&aring;et p&aring; b&oslash;rnehjem i Danmark s&aelig;rligt gennem 1960&rsquo;erne og 1970&rsquo;erne. I \"Dem, der ikke tier\" giver han endeligt ofrenes m&oslash;rke fort&aelig;lling en stemme. I l&oslash;bet af bogen belyses de tragiske h&aelig;ndelser p&aring; b&oslash;rnehjemmet Godhjem, p&aring; det lutherskmissionske b&oslash;rnehjem Solg&aring;rden i Tarm, hvor pigerne blev misbrugt gennem 15 &aring;r af forstanderen og p&aring; Det Kongelige Opfostringshus i nordsj&aelig;llandske Helleb&aelig;k, hvor drenge i to &aring;rtier blev misbrugt, ofte under bed&oslash;velse, af l&aelig;rere og socialr&aring;dgivere. Selvom mange kendte til disse ugerninger, blev b&oslash;rn og ansattes anmeldelser afvist eller undertrykt.</p>', 'dem der ikke tier.jpg'),
(50, 'Krystaller', 'Noell Elise Wakeroots', 'Krop og sjæl', 'Grønningen 1', 'Dansk', '2022-05-18 00:00:00', 'Hardcover', 0, '239.95', '<p>L&aelig;r om krystallernes historie &ndash; og om deres energi.L&aelig;r at bruge krystaller i din hverdag. De er mystiske, men ogs&aring; konkrete redskaber, du kan bruge til at skabe ro og til at opn&aring; det, du dr&oslash;mmer om. Krystaller indeholder tusinder af &aring;rs spirituel visdom. De har n&aelig;sten altid v&aelig;ret en del af vores liv. Vores forf&aelig;dre bar de smukke sten som amuletter, for s&aring;dan kunne de p&aring;virke deres rejse gennem livet og d&oslash;den. Og for dem bet&oslash;d smykket lykke, styrke og beskyttelse. I dag er det anderledes. De skinnende krystaller v&aelig;kker m&aring;ske vores nysgerrighed, men de f&aring;r os ogs&aring; til at stille sp&oslash;rgsm&aring;l: Hvad kan de egentlig? Hvordan bruger man dem, og skal man v&aelig;lge den lille r&oslash;de krystal eller den store hvide?</p>', 'krystaller.jpg'),
(51, 'Hobbitten', 'J.R.R. Tolkien', 'Skønlitteratur ', 'Gyldendal ', 'Dansk', '2019-06-14 00:00:00', 'Paperback', 336, '199.94', '<p>Hobbitten er Tolkiens ud&oslash;delige romanklassiker om hobbitten Bilbo S&aelig;kker, der meget mod sin vilje bliver udpeget af troldmanden Gandalf til at ledsage tretten dv&aelig;rge p&aring; deres generobringstogt af den enorme skat, der nidk&aelig;rt vogtes af dragen Smaug. Og som undervejs tilf&aelig;ldigt render ind i m&oslash;rkev&aelig;senet Gollum og vinder hans m&aelig;rkelige ring fra ham i en dyst om ordspil og g&aring;der.</p>', 'hobbitten.jpg'),
(52, 'Af blod og støv', 'Julie M. Day ', 'Fantasi ', 'Turbine', 'Dansk', '2020-05-25 00:00:00', 'Hardcover', 432, '189.95', '<p>Den unge heks Yara og hendes s&oslash;ster m&aring; flygte for livet efter, at hun afvises af &aring;nderne under hendes indvielsesritual til heksenes kreds, der udvikler sig katastrofalt. Krigerkvinden Zola forventer at blive k&aring;ret til sin stammes nye leder, da hendes landsby pludselig bliver angrebet af fremmede m&aelig;nd, som vil indfange slaver. De to venner Philip og Taran lever et roligt liv i deres lille landsby. Men alt &aelig;ndrer sig drastisk efter nye skels&aelig;ttende direktiver fra hovedstaden. Imens bliver kronprinsen til kongen af Kalos ufrivilligt sendt over Salthavet for at blive giftet bort i dv&aelig;rgenes land, som en del af kongens forhandlinger.</p>', 'af blod og støv.jpg'),
(53, 'Icebreaker', 'Hannah Grace', 'Engelsk fiktion', 'Simon & Schuster', 'Engelsk', '2023-01-19 00:00:00', 'Paperback', 448, '109.94', '<p>In Hannah Grace&rsquo;s \"Icebreaker\" we follow the talented ice skater Anastia Allen. She has worked hard all her life to get a chance at the Team USA, and finally it seems she will get to live her dream with a full scholarship at University of California and a place on their competitive figure skating team. Meanwhile the captain of the hockey team, Nate Hawkins, is focused on keeping his team on the ice as much as possible, when they are forced to share it with the figure skating team. Anastasia can&rsquo;t stand Nate, but while her skating partner is out she is forced to work very closely with Nate if she wants to keep her dream alive&hellip;</p>', 'icebreaker.webp'),
(54, 'Nattergalen', 'Kristin Hannah ', 'Skønlitteratur ', 'Cicero', 'Dansk', '2017-06-16 00:00:00', 'Paperback', 464, '169.94', '<p>I den lille franske by Carriveau i &aring;ret 1939 er Vianne Mauriac alene tilbage med sin datter Sophie, efter at hendes mand, Antoine, er taget til fronten. Da tyskerne bes&aelig;tter store dele af landet, m&aring; Vianne v&aelig;lge imellem at opgive deres lille hus eller have en tysk kaptajn indkvarteret. Og det er bare det f&oslash;rste af en r&aelig;kke sv&aelig;re valg, hun m&aring; tr&aelig;ffe for at beskytte sig selv og sin datter, mens hun venter p&aring; nyt om Antoine.</p>\r\n<p>Viannes lilles&oslash;ster Isabelle er hos deres far i Paris, da tyskerne invaderer byen. Sammen med tusindvis af andre parisere forlader hun byen og drager til fods mod Carriveau. P&aring; vejen oplever hun krigens gru p&aring; n&aelig;rmeste hold og m&oslash;der en ung modstandsmand, som hun forelsker sig hovedl&oslash;st i. Men da han svigter hende, m&aring; hun blive hos Isabelle i Carriveau, hvor hun involverer sig i modstandskampen og gang p&aring; gang s&aelig;tter livet p&aring; spil for at redde andre og for et frit Frankrig.</p>', 'nattergalen.jpg'),
(55, 'Dybet', 'Michael Katz Krefeld ', 'Krimi', 'Lindhardt & Ringhof', 'Dansk', '2020-06-17 00:00:00', 'Paperback', 408, '129.94', '<p>Ondskaben kender ingen gr&aelig;nser. Den erfarne privatopdager Ravn f&aring;r sin mest uhyggelige sag til dato, da en klient beder ham finde en gammel skolekammerat, som han ikke har haft kontakt med i 17 &aring;r. En r&aelig;kke bestialske overfald p&aring; kvinder, der ryster K&oslash;benhavn, har givet klienten mistanke om, at hans skolekammerat st&aring;r bag, fordi overfaldene minder om det, som han og kammeraten begik p&aring; en lille pige tilbage i 1993, og som endte fatalt. Af frygt for h&aelig;vnangreb mod drengene har de siden deres frigivelse levet under politiets vidnebeskyttelsesprogram med nye hemmelige identiteter og er derfor umulige at opspore. Da endnu en kvinde bliver overfaldet og denne gang dr&aelig;bt, efterforsker Ravn sagen og indleder jagten p&aring; den anonyme morder. En gerningsmand der kan v&aelig;re hvem som helst, og sl&aring; til hvorn&aring;r det skal v&aelig;re. Og sp&oslash;rgsm&aring;let melder sig hurtigt for Ravn, om han kender sin klients virkelige identitet og hans motiver? Dybet er fjerde selvst&aelig;ndige bog i Michael Katz Krefelds popul&aelig;re serie om privatopdageren Ravn, der bor p&aring; sin b&aring;d i Christianshavns kanal sammen med sin engelske bulldog M&oslash;ffe.</p>', 'dybet.jpg'),
(56, 'Passage', 'Cathrine Laudrup-Dufour', 'Biografi', 'Grønningen 1', 'Dansk', '2023-10-09 00:00:00', 'Hardcover', 355, '299.94', '<p>Cathrine Laudrup-&shy;Dufours Passage er en ekstra&shy;ordin&aelig;r elitesportsfort&aelig;lling om str&aelig;ben efter perfektionen i den fuldkomne symbiose mellem rytter og hest &ndash; og en dybt personlig frig&oslash;relses&shy;fort&aelig;lling om kampen for at finde sin egen m&aring;de at &shy;forvalte sit talent og sin &shy;personlighed p&aring;.I sin selvbiografi giver &shy;Cathrine Laudrup-Dufour l&aelig;seren et ufiltreret og unikt indblik i, hvad det har kostet Danmarks mest vindende dressurrytter at n&aring; sine sportslige m&aring;l og indfri den ultimative dr&oslash;m om at blive en af verdens bedste dressur&shy;ryttere &ndash; og kunne leve af sin passion. Hun bliver tr&aelig;net af to af verdens bedste dressurryttere: prinsesse Nathalie Zu-Sayn Wittgenstein og den legendariske OL-rytter Kyra Kyrklund. I 2021 giftede hun sig med &shy;springrytter Rasmine Laudrup-Dufour og blev en del af Danmarks st&oslash;rste sportsfamilie. I denne bog fort&aelig;ller hun for f&oslash;rste gang om alle sine sejre &ndash; og om bagsiden af medaljen. Som 12-&aring;rig kom Cathrine p&aring; pony-landsholdet &ndash; og har v&aelig;ret i toppen af dansk ridesport siden. Samme &aring;r vandt hun DM. Siden har hun deltaget i to olympiader og vundet et hav af h&aelig;derspriser og utallige medaljer ved DM, EM, Nordisk Mesterskab. I 2022 bragte hun VM-guldet hjem sammen med det danske dressurlandshold for f&oslash;rste gang nogen&shy;sinde. Hendes karriere er fuld af sejre. Men ogs&aring; nederlag, menneskelige omkostninger og personlige tab. &Eacute;n pris for succesen er, at hun har mistet kontakten til en del af sin familie. Cathrine Laudrup-&shy;Dufour er f&oslash;dt i 1992 i Hvals&oslash;. Hun er gift med springrytter Rasmine Laudrup-Dufour. De bor p&aring; en g&aring;rd i Fredensborg, hvorfra de driver deres forretning. Cathrine Laudrup-Dufour er den mest vindende danske dressurrytter nogensinde.</p>', 'passage.jpg'),
(57, 'Bogen om Badehotellet', 'Jacob Wendt Jensen ', 'Biografi', 'Peoples Press', 'Dansk', '2023-02-26 00:00:00', 'Hardcover', 300, '299.94', '<div role=\"none\">\r\n<div role=\"none\">\r\n<div role=\"none\">\r\n<div role=\"none\">\r\n<div>\r\n<div role=\"none\">\r\n<div role=\"none\">\r\n<div role=\"none\">\r\n<div dir=\"auto\" role=\"none\">I Bogen om Badehotellet g&aring;r Jacob Wendt Jensen bag om tilblivelsen af den popul&aelig;re tv-serie fra id&eacute; til seersucces. Resultatet er blevet en unik og underholdende fort&aelig;lling, sp&aelig;kket med anekdoter, flotte fotos og nyt materiale. Fra forfatternes f&oslash;rste m&oslash;de, casting og l&aelig;sepr&oslash;ver, over kostumer, musik og lyd, til kulisser, mad og blomster. Bogen er baseret p&aring; interviews med mere end 40 personer, der alle har spillet en rolle i eller omkring serien. Badehotellet er en komedie-drama-serie, skabt af Stig Thorsboe og Hanna Lundblad for TV 2. Den havde premiere i 2013og best&aring;r forel&oslash;big af ni s&aelig;soner med i alt 55 episoder. Tiende og sidste s&aelig;son vises i 2024. Serien er blevet en enorm succes med et seertal p&aring; 1,9 mio. Den f&oslash;lger hverdagen hos Andersens Badehotel i Nordjylland, hvor velhavende familier fra K&oslash;benhavn tilbringer deres somre. Serien skildrerhotellets ansatte og g&aelig;ster og deres indbyrdes forhold fra 1928 og frem til1946, mens en ny verdenskrig bliver stadig vanskeligere at holde p&aring; afstand.</div>\r\n</div>\r\n</div>\r\n<div role=\"none\">\r\n<div role=\"none\">&nbsp;</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div role=\"none\">\r\n<div role=\"none\">&nbsp;</div>\r\n</div>\r\n</div>\r\n<div role=\"none\">&nbsp;</div>\r\n</div>\r\n<div role=\"none\">\r\n<div aria-hidden=\"true\">\r\n<div role=\"none\">\r\n<div role=\"none\">\r\n<div>\r\n<div style=\"list-style-type: none;\" tabindex=\"0\" role=\"button\" aria-label=\"Reager\" aria-haspopup=\"menu\" aria-expanded=\"false\">\r\n<div>\r\n<div>&nbsp;</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div>\r\n<div>\r\n<div style=\"list-style-type: none;\" tabindex=\"0\" role=\"button\" aria-label=\"Svar\">\r\n<div>&nbsp;</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div>\r\n<div style=\"list-style-type: none;\" tabindex=\"0\" role=\"button\" aria-label=\"Mere\" aria-haspopup=\"menu\" aria-expanded=\"false\">\r\n<div>\r\n<div>&nbsp;</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div role=\"none\">\r\n<div role=\"none\">&nbsp;</div>\r\n</div>\r\n</div>\r\n<div role=\"none\">\r\n<div role=\"none\">&nbsp;</div>\r\n</div>\r\n</div>\r\n<div>\r\n<div>&nbsp;</div>\r\n</div>', 'bogen-om-badehotellet.jpg'),
(58, 'En dag vil vi grine af det', 'Thomas Korsgaard', 'Roman', 'Lindhardt & Ringhof', 'Dansk', '2019-09-20 00:00:00', 'Paperback', 320, '100.00', '<p>Hvad sker der med en familie i underskud, som pludselig kommer til penge? Som endelig f&aring;r det, de har dr&oslash;mt om? Vil alt nu endelig blive godt i hjemmet for enden af den lange grusvej lidt uden for Skive? En dag vil vi grine af det er en sorgmunter roman om at skulle klare sig som ung mand i udkanten af det danske velf&aelig;rdssamfund.Tues mor har f&aring;et en stor erstatning for en arbejdsskade, og nu skal alt blive godt. Men er penge det, der skal til, for at komme fri af den f&oslash;lelse af rod og opl&oslash;sning, der hidtil har pr&aelig;get dagligdagen? Og hvad sker der, n&aring;r Tue ikke l&aelig;ngere er et barn - men en ung voksen, som opdager, at der er en verden uden for hjemmet for enden af grusvejen?Thomas Korsgaard tog l&aelig;sere og anmeldere med storm med sin debutroman Hvis der skulle komme et menneske forbi. Nu forts&aelig;tter den st&aelig;rke fort&aelig;lling om Tue, der vokser op i et hjem, hvor b&oslash;rn overlades til sig selv, hvor voksne ikke rigtig magter at v&aelig;re for&aelig;ldre - og hvor realiteterne sj&aelig;ldent lever op til intentionerne.Thomas Korsgaard modtog i 2022 De gyldne laurb&aelig;r for Man skulle nok have v&aelig;ret der, bind 3 i trilogien om Tue.</p>', 'en dag vil vi grine af det.jpg'),
(59, 'Fifty Shades - Fanget', 'E. L. James', 'Erotisk Roman', 'Pretty Ink', 'Dansk', '2012-08-31 00:00:00', 'Paperback', 544, '149.93', '<p>Anastasia er litteraturstuderende og ender tilf&aelig;ldigvis med at f&aring; en hurtig tjans ved universitetsbladet. Hun v&aelig;lter bogstavligt talt ind i Christian Greys verden, da hun skal interviewe ham, og det skal vise sig at udvikle sig til en forvirrende, frustrerende og vanvittig forelskelse i en m&oslash;rk, g&aring;de- og magtfuld mand. Lidenskab og beg&aelig;r blusser op mellem parterne, men da smukke Christian Grey gerne vil introducere Anastasia til sin m&oslash;rkere erotiske side &ndash; som indeb&aelig;rer en kontrakt om et S/M-forhold &ndash; bliver hun i tvivl. Kan hun lide at lade sig undertrykke af en mand? T&oslash;r hun?</p>', 'fifty shades.jpg'),
(60, 'Kunsten at være fucking ligeglad', 'Mark Manson', 'Sundhed/Livsstil ', 'Memoris', 'Dansk', '2018-11-02 00:00:00', 'Hardcover', 220, '229.95', '<p>Er du ogs&aring; d&oslash;dtr&aelig;t af selvhj&aelig;lpsb&oslash;ger, der fort&aelig;ller dig, at bare du er glad og positiv, s&aring; skal det nok g&aring; alt sammen? I Kunsten at v&aelig;re fucking ligeglad finder du den stik modsatte tilgang: Livet er fyldt med problemer, og du slipper aldrig for dem. Kunsten er at finde ud af, hvad der er vigtigt for dig. Du er n&oslash;dt til at v&aelig;lge, hvilke problemer du vil have i dit liv, og hvilke du bare vil springe op og falde ned p&aring;.</p>', 'kunsten at være fucking ligeglad.webp');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
